[CmdletBinding()]
param(
  [string]$InputDirectory = "assets/talking_head",
  [string]$OutputDirectory = "assets/talking_head/processed",
  [string]$FfmpegPath = "ffmpeg",
  [string]$FfprobePath = "ffprobe",
  [string]$SourceDescription,
  [string]$UsageRights,
  [switch]$ValidateOnly
)

$ErrorActionPreference = "Stop"
$expectedShots = 1..11 | ForEach-Object { "shot$_.mp4" }

function Get-MediaInfo {
  param([string]$Path)

  $raw = & $FfprobePath -v error -show_entries format=duration,size:stream=codec_name,codec_type,width,height -of json $Path
  if ($LASTEXITCODE -ne 0) {
    throw "ffprobe could not inspect '$Path'."
  }

  return $raw | ConvertFrom-Json
}

if (-not (Get-Command $FfmpegPath -ErrorAction SilentlyContinue)) {
  throw "ffmpeg wurde nicht gefunden: $FfmpegPath"
}

if (-not (Get-Command $FfprobePath -ErrorAction SilentlyContinue)) {
  throw "ffprobe wurde nicht gefunden: $FfprobePath"
}

$missingShots = $expectedShots | Where-Object { -not (Test-Path (Join-Path $InputDirectory $_)) }
if ($missingShots) {
  throw "Required input files are missing: $($missingShots -join ', ')"
}

$inputFiles = $expectedShots | ForEach-Object { Join-Path $InputDirectory $_ }
foreach ($inputFile in $inputFiles) {
  $info = Get-MediaInfo -Path $inputFile
  $video = $info.streams | Where-Object { $_.codec_type -eq "video" } | Select-Object -First 1
  $audio = $info.streams | Where-Object { $_.codec_type -eq "audio" } | Select-Object -First 1

  if (-not $video -or -not $audio) {
    throw "'$inputFile' needs both a video and an audio stream."
  }
}

if ($ValidateOnly) {
  Write-Output "All eleven input files are present and include video plus audio."
  exit 0
}

if ([string]::IsNullOrWhiteSpace($SourceDescription) -or [string]::IsNullOrWhiteSpace($UsageRights)) {
  throw "Provide -SourceDescription and -UsageRights to create the media manifest."
}

New-Item -ItemType Directory -Force -Path $OutputDirectory | Out-Null
$manifestRows = [System.Collections.Generic.List[string]]::new()
$sourceHashRows = [System.Collections.Generic.List[string]]::new()
$fontPath = "C\:/Windows/Fonts/arialbd.ttf"
$watermarkFilter = "drawtext=fontfile='$fontPath':text='AI':fontcolor=white:fontsize=28:box=1:boxcolor=black@0.68:boxborderw=8:x=w-text_w-20:y=h-text_h-20"

foreach ($inputFile in $inputFiles) {
  $fileName = Split-Path -Leaf $inputFile
  $outputFile = Join-Path $OutputDirectory $fileName

  & $FfmpegPath -hide_banner -loglevel error -y -i $inputFile -map 0:v:0 -map 0:a? -vf $watermarkFilter -c:v libx264 -preset slow -crf 25 -pix_fmt yuv420p -c:a aac -b:a 96k -af "aresample=async=1:first_pts=0" -movflags +faststart $outputFile
  if ($LASTEXITCODE -ne 0) {
    throw "ffmpeg could not process '$fileName'."
  }

  $inputInfo = Get-MediaInfo -Path $inputFile
  $outputInfo = Get-MediaInfo -Path $outputFile
  $outputVideo = $outputInfo.streams | Where-Object { $_.codec_type -eq "video" } | Select-Object -First 1
  $sourceHash = (Get-FileHash -LiteralPath $inputFile -Algorithm SHA256).Hash
  $sourceSize = [int64]$inputInfo.format.size
  $outputSize = [int64]$outputInfo.format.size
  $duration = [math]::Round([double]$outputInfo.format.duration, 3)
  $sizeChange = [math]::Round((1 - ($outputSize / $sourceSize)) * 100, 1)

  if ($outputSize -ge $sourceSize) {
    throw "'$fileName' is not smaller than its source file. Processing stopped."
  }

  $manifestRows.Add("| $OutputDirectory/$fileName | $duration s | $($outputVideo.width)x$($outputVideo.height) | H.264/AAC MP4 | $sourceSize B -> $outputSize B ($sizeChange% smaller) | $SourceDescription | $UsageRights | AI generated or AI modified | AI burned in at bottom right | Planned for on-demand scene loading in #26 |")
  $sourceHashRows.Add("| $fileName | $sourceHash |")
}

$manifestPath = Join-Path (Resolve-Path $InputDirectory) "MEDIA_MANIFEST.md"
$manifest = @(
  "# Talking Head media manifest",
  "",
  "Generated by scripts/prepare-talking-head-videos.ps1. On-demand scene loading is implemented by the follow-up story #26.",
  "",
  "## AI transparency assessment",
  "",
  "These clips are realistic AI-generated depictions based on the project owner's own face. A realistic synthetic talking head may be mistaken for an authentic recording. A visible AI label is therefore used as a transparency measure under Article 50 of the EU AI Act. The white AI label on a black background is permanently burned into the lower-right corner of every clip and is visible at first perception.",
  "",
  "## Source archive and reproduction",
  "",
  "The unprocessed source videos are retained in a restricted local archive controlled by the project owner and are intentionally excluded from the published repository and GitHub Pages. To reproduce this batch, request the source archive from the project owner, verify the SHA-256 checksums below, place the files as assets/talking_head/shot1.mp4 through shot11.mp4, and run this script with the documented source and rights parameters.",
  "",
  "| Source file | SHA-256 |",
  "| --- | --- |"
) + $sourceHashRows + @(
  "",
  "## Final assets",
  "",
  "| Final asset path | Duration | Dimensions | Format | Optimization | Source | Usage rights | AI status | Label | Planned loading behavior |",
  "| --- | ---: | --- | --- | --- | --- | --- | --- | --- | --- |"
) + $manifestRows

[System.IO.File]::WriteAllLines($manifestPath, $manifest, [System.Text.UTF8Encoding]::new($false))
Write-Output "Eleven videos processed: $OutputDirectory"
Write-Output "Media manifest created: $manifestPath"
